### ISSUE TITLE
error writing into a file

### ISSUE THREAD

**Issue by sewbacca** [jasongronn/NyanOS#5]
After cloning the repository and setting a new password, it attempt to call nil in NyanOs/newpassword on line 35.

**Comment by jasongronn** [comment]
Should now work.

**Comment by sewbacca** [comment]
It still doesn't work.

**Comment by sewbacca** [comment]
The complete file system doesn't work correctly.

**Comment by jasongronn** [comment]
I tried it (newPassword) on Saturday, worked just fine. Don't know what you mean

**Comment by jasongronn** [comment]
Computercraft forums are down?

**Comment by sewbacca** [comment]
Still the file system doesn't work:
lua> io.open('example', 'w')
-> return nil

**Comment by jasongronn** [comment]
Were still interested in this? Okay!

**Comment by jasongronn** [comment]
Im back! (But not full-time)
